mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: vue_go
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: "2023-06-09"
  bei_an: "nynu"
  title: "123"
  qq_image: "http://www.fengfengzhidao.com/static/my/img/footer/qq.png"
  version: "6.0.2"
  email: "2693079065@qq.com"
  wechat_image: "http://www.fengfengzhidao.com/static/my/img/footer/wechat.png"
  name: "个人博客"
  job: "毕业设计"
  addr: "nynu"
  slogan: "个人"
  slogan_en: "GEREN"
  web: "http://www.fengfengzhidao.com"
  bilibili_url: "123"
  gitee_url: "123"
  github_url: "123"
qq:
  app_id: xxx
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
qi_niu:
  enable: true
  access_key: je3pfQ0XQdoHXAj7pDxuARDhI46EAKnLIl4g3A6Y
  secret_key: j6OyPztxb3tKPkFIsVoHnIEh4-jmMVyTgn37oVDX
  bucket: nynugerenboke
  cnd: http://rwahp1j5k.hn-bkt.clouddn.com/
  prefix: "gvb"
  zone: z2
  size: 5
jwt:
  secret: xxx
  expires: 2
  issuer: "nynu.cn"
email:
  host: smtp.qq.com
  port: 465
  user: 2693079065@qq.com
  password: mqpgmfpvcncvddfd
  default_from_email: 个人博客
  use_ssl: true
  use_tls: false
redis:
  ip: 127.0.0.1
  port: 6379
  password: "redis"
  pool_size: 100

